### ISSUE TITLE
It doesnt work lol

### ISSUE THREAD

**Issue by Infraction7** [PY44N/LuaObfuscatorV2#12]
```Program Error:
lua: cannot open temp4.lua: No such file or directory

thread 'main' panicked at 'Failed to copy final file: Os { code: 2, kind: NotFound, message: "Не удается найти указанный файл." }', src\main.rs:107:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by PY44N** [comment]
Would you be willing to send the file you used to get that error?

**Comment by Marko97IT** [comment]
I got the same error ...

**Comment by Marko97IT** [comment]
> > I got the same error ...
> 
> Would you be willing to email me the file you tried using? [pyan4444@gmail.com](mailto:pyan4444@gmail.com)

I sended you an email with a sample script right now.

**Comment by PY44N** [comment]
> > > I got the same error ...
> > 
> > 
> > Would you be willing to email me the file you tried using? [pyan4444@gmail.com](mailto:pyan4444@gmail.com)
> 
> I sended you an email with a sample script right now.

Thanks. c93a4780775db887c245647610b6fe8a660d4ab3 should have fixed your issue. Let me know if you have any other problems

**Comment by Marko97IT** [comment]
> > > > I got the same error ...
> > > 
> > > 
> > > Would you be willing to email me the file you tried using? [pyan4444@gmail.com](mailto:pyan4444@gmail.com)
> > 
> > 
> > I sended you an email with a sample script right now.
> 
> Thanks. [c93a478](https://github.com/PY44N/LuaObfuscatorV2/commit/c93a4780775db887c245647610b6fe8a660d4ab3) should have fixed your issue. Let me know if you have any other problems

Can you publish a compiled version into releases (Windows)? Thank you.

**Comment by Marko97IT** [comment]
@PY44N the same error is showing up again.
