### ISSUE TITLE
Help me PY44N

### ISSUE THREAD

**Issue by JuJu888881** [PY44N/LuaObfuscatorV2#14]
I'm a beginner but I'm a self-taught person because I want to learn about luascript. I'm leaving a comment because I got an error while using your program.
------

C:\Users\master\Downloads\LuaObfuscatorV2-main\LuaObfuscatorV2-main\LuaObfuscatorV2\target\release>lua_obfuscator.exe Input.lua
["lua_obfuscator.exe", "Input.lua"]
[Obfuscator] Encrypting Constants...
[Obfuscator] Compiling...
[Obfuscator] Reading file...
thread 'main' panicked at src\main.rs:66:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "지정된 파일을 찾을 수 없습니다.(It means 'Cant find file.)" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

--------------------

I put the Input.lua file and lua_obfuscator.exe file in the same folder for sure, but it doesn't recognize it in cmd. I'm asking for help. What should I do?

![5555](https://github.com/PY44N/LuaObfuscatorV2/assets/158476038/7fd16fae-b573-457c-92fd-9650bcbc6fd4)

**Comment by PY44N** [comment]
The Lua version the obfuscator uses (5.1) does not support unicode characters, so the input code can only contain ascii characters

Table of all ascii characters:
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/62762243/294eeb17-4c41-43f0-b582-fdfec019cd17)
