### ISSUE TITLE
Help PY44N

### ISSUE THREAD

**Issue by Raze-Scripts** [PY44N/LuaObfuscatorV2#15]
i cant obfuscate my fivem lua
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/2c9564b5-6d03-42fd-8dfe-fc034064a261)

**Comment by PY44N** [comment]
It's looking for a file called "main.lua" is your code in that file?

**Comment by RazeUtilities** [comment]
yes

**Comment by PY44N** [comment]
If you run

luac main.lua

does it compile?

**Comment by RazeUtilities** [comment]
no

**Comment by PY44N** [comment]
What error message does it give?

**Comment by RazeUtilities** [comment]
i have server.lua
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/df0a2480-45d0-4496-85aa-b27a83b9c27a)
then i run
cargo run server.lua
then this is the error
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/af4e0e73-8326-4b62-9adc-cf7fc4bd04a7)

**Comment by PY44N** [comment]
What error do you get when you run luac server.lua?

**Comment by RazeUtilities** [comment]
here 
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/259e8b2b-6b90-478e-9a58-84bc062afce2)

**Comment by RazeUtilities** [comment]
Update?

**Comment by PY44N** [comment]
Can you try just opening the directory in your terminal and just typing luac server.lua without any cargo things?

**Comment by RazeUtilities** [comment]
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/d39d2864-17c5-4bb3-995c-bf2db12580c2)

the output
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/0b0107f3-e37c-4d27-9218-8c4d8f977e08)

**Comment by RazeUtilities** [comment]
i try to run cargo run server.lua
![image](https://github.com/PY44N/LuaObfuscatorV2/assets/105653892/99899d18-bb4b-470e-9f62-468c3498c289)
