### ISSUE TITLE
Constant dump issue

### ISSUE THREAD

**Issue by N-ov** [PY44N/LuaObfuscatorV2#18]
Hello, I tried running the example code and after ~10 minutes of analysis, I found a method to constant dump all the functions and constants.

The code is here: 
```lua
local oldUnpack = unpack
unpack = function(...)
	print(...)
	return oldUnpack(...)
end
--[[
Output:
{
  [0] = "function",
  [1] = "Hello World"
}
]]
```

Overall, this is a great way to secure your local scripts.

**Comment by PY44N** [comment]
This should be fixed in eb5aba74424255fc61558f57c63d7fb2e411bf27
