### ISSUE TITLE
Error after ofuscate

### ISSUE THREAD

**Issue by niklas-wulff** [PY44N/LuaObfuscatorV2#7]
Code before: 

`lua
local test = 2

function testFunc()
	print('Deine Zahl ist:' .. test)
end
`

Code after run "cargo run test.lua"

Error:

Program Error:
lua: @temp2.lua:0:temp4.lua:1: 'for' limit must be a number
stack traceback:
        [C]: in function 'u'
        temp4.lua:1: in function '_0f'
        temp4.lua:1: in function <temp4.lua:1>
        temp4.lua:1: in function 'a'
        temp4.lua:1: in main chunk
        [C]: ?

**Comment by PY44N** [comment]
This should have been fixed by #9
