### ISSUE TITLE
cargo run fails

### ISSUE THREAD

**Issue by Infraction7** [PY44N/LuaObfuscatorV2#8]
`cargo run filename.lua` errors with following:
![cmd_mN13m3acgA](https://github.com/PY44N/LuaObfuscatorV2/assets/112822467/b63e9072-8af1-489d-b3c3-9baf932be0d7)

**Comment by PY44N** [comment]
I made a prebuilt version for Windows that should work. Just download the zip from the [releases page](https://github.com/PY44N/LuaObfuscatorV2/releases/tag/v0.1.0) and run
```
.\lua_obfuscator.exe YOURFILE.lua
```
